tools/syz-declextract: don't analyze host files
I've got this error when trying to run the tool:

arch/x86/tools/relocs_64.c: In file included from arch/x86/tools/relocs_64.c:2:
In file included from arch/x86/tools/relocs.h:5:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found

The arch/x86/tools/relocs_64.c is part of some host tool
that was compiled with gcc. And probably my clang installation
is somehow broken and can't compile normal user-space C programs.

Skip files that were not compiled with clang.
We don't need to analyze them (host tools),
and it also solves my clang problem.