prog: support int8 resources in any squashing
We've got the following panic:

--- FAIL: TestMutateRandom (7.77s)
    export_test.go:37: seed=1655724857302243235
    --- FAIL: TestMutateRandom/test/32_shmem (0.00s)
panic: bad size [recovered]
	panic: bad size
goroutine 562 [running]:
panic({0x5ea5a0, 0x8dade8})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/google/syzkaller/prog.(*Target).squashResult(0xc0002a9ba0, 0xc026faa7b0, 0xc026ad1bc8)
	/syzkaller/gopath/src/github.com/google/syzkaller/prog/any.go:236 +0x2d1

This happens because we try to squash resource of size 1.
While we still don't have such resources in real descriptions,
we've got one in test descriptions (added in out_overlay change).

Support int8 resources in squashing procedure.