executor: apply optnone to guest_handle_nested_vmentry_intel()
Florent Revest reported ThinLTO builds failing with the following error:

  <inline asm>:2:1: error: symbol 'after_vmentry_label' is already defined
  after_vmentry_label:
  ^
  error: cannot compile inline asm

, which turned out to be caused by the compiler not respecting `noinline`.

Adding __attribute__((optnone)) (or optimize("O0") on GCC) fixes the issue.