prog: fix episodic failures to generate a call
Tests sometimes fail as:

--- FAIL: TestCreateResourceRotation (0.97s)
    ...
    resources_test.go:181: testing call syz_io_uring_submit
    resources_test.go:187: failed to create resource fd_dir
FAIL

Almost always it's related to fd_dir resource.

The problem is with no_generate syscalls (we have lots of
no_generate mount syscalls that produce fd_dif).
Rotator considers them as legit resource ctors,
but the actual code in createResource does not.
As the result Rotator creates subsets of syscalls
where not all resources can be created.

The same problem affects TransitivelyEnabledCalls.
It may leave syscalls that require resources produced only
by no_generate syscalls. We won't be able to produce such
resources during fuzzing.

Split Syscall.outputResources to createResources
(can actually be used to create, excludes no_generate)
and usesResources, this includes no_generate syscalls.