.github/workflows: support errors from golangci-lint
If there are compilation errors in tests, golangci-lint
produces then in the following format:

level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/syzkaller/gopath/src/github.com/google/syzkaller/syz-fuzzer/mab_reward_test.go:26:35: cannot use rawCov (variable of type []float64) as float64 value in argument to status.Reward.RawAllTasks.Update /syzkaller/gopath/src/github.com/google/syzkaller/syz-fuzzer/mab_reward_test.go:26:43: cannot use rawTime (variable of type []float64) as float64 value in argument to status.Reward.RawAllTasks.Update /syzkaller/gopath/src/github.com/google/syzkaller/syz-fuzzer/mab_reward_test.go:27:38: cannot use totalReward (variable of type []float64) as float64 value in argument to status.Reward.RewardAllTasks.Update /syzkaller/gopath/src/github.com/google/syzkaller/syz-fuzzer/mab_reward_test.go:33:2: reward declared but not used]"

Transform this to github format.