pkg/cover: fix gcc build error due to warning triggered by -Wint-conversion
This error has appeared on Fedora 40 s390x with gcc 14.0.1.

$ go test -v -count=1 -short ./pkg/cover

/tmp/TestReportGeneratorlinux-s390xmismatch-pcs2143164880/001/kcov.c:20:33:
  error: pointer/integer type mismatch in conditional expression
  [-Wint-conversion]
20 |        return map ? map->l_addr : NULL;
   |                                 ^
At top level:
cc1: note: unrecognized command-line option
     '-Wno-unused-command-line-argument' may have been intended to silence
     earlier diagnostics

Signed-off-by: Alexander Egorenkov <eaibmz@gmail.com>