executor/linux: fix compilation error with old compilers
My gcc-10 in testing vm compainls during reproducer [0] build with
following error:

rep.c: In function ‘remove_dir’:
rep.c:662:3: error: a label can only be part of a statement and a declaration is not a statement
  662 |   const int umount_flags = MNT_FORCE | UMOUNT_NOFOLLOW;
      |   ^~~~~

Label followed by declaration is C23 extension, so only new compilers
support it.

Fix it by moving declaration above `retry` label and put unused attribute
to suppress possible warning.

[0] https://syzkaller.appspot.com/bug?extid=dcc068159182a4c31ca3

Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>