osutil: Added stubs for missing Darwin osutil routines.
These were copy-pasted from the Windows osutil routines.

These were preventing go get from succeeding:

    go get github.com/google/syzkaller/...

    # github.com/google/syzkaller/pkg/ipc
    ../go-root-syzkaller/src/github.com/google/syzkaller/pkg/ipc/ipc.go:634:2: undefined: osutil.UmountAll