tools: update buildroot version
2021.08.x does not build on Linux 5.15+ due to the following error.

interpret.c:48:10: fatal error: linux/ipx.h: No such file or directory
   48 | #include <linux/ipx.h>

It was fixed in the newer buildroot versions.