sys/targets: fix BuildOS initialization for TestOS
Move the initialization of the target's BuildOS into initTarget()
function for TestOS because a correct value of BuildOS is required not to
falsely spoil native compiler binaries for TestOS and by that prevent
TestOS unit test from compiling.

$ go test -v -count=1 -run=TestCover/32 ./pkg/runtest/
=== RUN   TestCover
=== PAUSE TestCover
=== CONT  TestCover
=== RUN   TestCover/32
=== PAUSE TestCover/32
=== CONT  TestCover/32
    build.go:39: failed to build executor: failed to build program:

        compiler invocation: cant-build-test-on-linux
--- FAIL: TestCover (0.21s)
    --- FAIL: TestCover/32 (0.00s)
FAIL
FAIL    github.com/google/syzkaller/pkg/runtest 0.325s
FAIL

Signed-off-by: Alexander Egorenkov <eaibmz@gmail.com>